### ISSUE TITLE
Controls and pager

### ISSUE THREAD

**Issue by zergiocosta** [d48/zepto-carousel#1]
Is there an easy way to make controls and/or pager? Like `next`, `prev` and some pager to know how many slides are there?

Thank you! =)

**Comment by d48** [comment]
Sure, since you can always get the number of elements in the container, you essentially have a number to go on (1st element, 3rd element, etc). `next` and `prev` buttons will just cycle inline css setting for `opacity` for element next or previous in the DOM.

You would then just have to pass an option to the `.carousel()` method for pager or carousel controller = true. Did you want to try to hack at updating?

**Comment by zergiocosta** [comment]
Thank you! But I just wanted to know if it was already done for me to pass the related option to the function. I was looking for a zepto carousel to use in one of my projects. I liked your carousel more than the others. I just installed without controllers, but perhaps I will try to make this functionality. If I am able to do it in a good way and without dirty code I send you a pull request in a few days. If I am not, sorry. =(

Anyway, thank you and congratz for this nice carousel! =D

**Comment by d48** [comment]
Unfortunately that option is not there yet but for sure you're more than welcome to update. If I get to it some time I will post it up Thanks a lot!
